/**
 * LEARNING ENGINE — AUTO-GENERATION SCHEMA (IMMUTABLE)
 *
 * Every page generated by this system follows the same backbone.
 * Enables: trivia generation, cross-linking, UI predictability, validation.
 *
 * Philosophy: interconnected (mycelium), non-linear, exploratory.
 * Curiosity leads; content stands alone and connects outward.
 */

/* ========== INPUT PARAMETERS (MINIMAL) ========== */

export type TopicType =
  | "craft"
  | "stem"
  | "science"
  | "biography"
  | "culture"
  | "media"
  | "theory"
  | "geography";

export type DepthLevel = "overview" | "standard" | "deep_dive";
export type ImageDensity = "low" | "medium" | "high";

export type LearningGoal =
  | "hands-on understanding"
  | "conceptual learning"
  | "fun & curiosity"
  | "real-world connection";

export interface LearningEngineInput {
  topic_type: TopicType;
  primary_topic: string;
  target_audience: ("kids" | "teens" | "adults" | "mixed")[];
  depth_level: DepthLevel;
  image_density: ImageDensity;
  learning_goals: LearningGoal[];
}

/* ========== FIXED PAGE SECTION IDs (THE BACKBONE) ========== */

export const ENGINE_SECTION_IDS = [
  "hero_intro",
  "quick_wow",
  "core_concepts",
  "hands_on_or_examples",
  "difficulty_tiers",
  "variations_and_experiments",
  "real_world_connections",
  "cross_links",
  "trivia_seeds",
  "further_exploration",
] as const;

export type EngineSectionId = (typeof ENGINE_SECTION_IDS)[number];

/** All required section IDs for validation. */
export const REQUIRED_SECTION_IDS: EngineSectionId[] = [...ENGINE_SECTION_IDS];

/* ========== DIFFICULTY TIERS (MANDATORY) ========== */

export type DifficultyTierLabel = "quick_win" | "explorer" | "deep_dive";

export interface DifficultyTier {
  tier: DifficultyTierLabel;
  title: string;
  description: string;
  /** Optional: link to related topic slug or section. */
  relatedTopicId?: string;
}

/** Tier 1: Quick Win — immediate payoff, low effort. Tier 2: Explorer — variables, testing. Tier 3: Deep Dive — real science, systems. */
export interface DifficultyTiersBlock {
  tier1_quick_win: DifficultyTier;
  tier2_explorer: DifficultyTier;
  tier3_deep_dive: DifficultyTier;
}

/* ========== CROSS-LINKS (THE MYCELIUM) ========== */

export type CrossLinkType =
  | "concept_link"
  | "craft_link"
  | "biography_link"
  | "culture_link"
  | "modern_use_link";

export interface CrossLink {
  type: CrossLinkType;
  label: string;
  /** Target Learn slug or external URL. */
  targetId?: string;
  targetUrl?: string;
}

/** Minimum cross-links per page. */
export const MIN_CROSS_LINKS = 3;
export const MAX_CROSS_LINKS = 8;

/* ========== TRIVIA SEEDS (NOT QUESTIONS YET) ========== */

export type TriviaSeedType =
  | "fact"
  | "cause_effect"
  | "true_false_candidate"
  | "misconception"
  | "historical_note";

export interface TriviaSeed {
  type: TriviaSeedType;
  content: string;
}

/** Minimum trivia seeds per page. */
export const MIN_TRIVIA_SEEDS = 5;

/* ========== IMAGE SLOT RULES ========== */

export const IMAGE_RULES = {
  min_images: 3,
  /** Dynamic by depth_level: overview=3, standard=5, deep_dive=8 or more. */
  placement: [
    { sectionId: "hero_intro" as EngineSectionId, role: "hero", count: 1 },
    { sectionId: "core_concepts" as EngineSectionId, role: "diagram", count: 1 },
    { sectionId: "hands_on_or_examples" as EngineSectionId, role: "step", count: 1 },
    { sectionId: "variations_and_experiments" as EngineSectionId, role: "context", count: 0 },
  ] as const,
} as const;

export interface EngineImageSlotMeta {
  sectionId: EngineSectionId;
  slotId: string;
  role: "hero" | "context" | "diagram" | "step" | "comparison";
  source?: string;
  licenseType?: string;
  attributionText?: string;
  confidenceScore?: number;
}

/* ========== ENGINE SECTION (ONE SECTION OF A GENERATED PAGE) ========== */

export interface EngineContentBlock {
  type: "paragraph" | "bullet-list" | "callout" | "divider";
  content: string | string[];
  emphasis?: "normal" | "highlight" | "warning" | "fun-fact";
}

export interface EngineSection {
  id: EngineSectionId;
  title: string;
  contentBlocks: EngineContentBlock[];
  imageSlots?: EngineImageSlotMeta[];
}

/* ========== GENERATED PAGE (OUTPUT OF THE ENGINE) ========== */

export interface GeneratedLearningPage {
  id: string;
  slug: string;
  topic: string;
  type: TopicType;
  title: string;
  subtitle?: string;
  /** For UI and filtering. */
  target_audience: ("kids" | "teens" | "adults" | "mixed")[];
  depth_level: DepthLevel;
  sections: EngineSection[];
  difficulty_tiers: DifficultyTiersBlock;
  cross_links: CrossLink[];
  trivia_seeds: TriviaSeed[];
  /** Optional: topics/concepts for trivia and tags. */
  topics?: string[];
  concepts?: string[];
  metadata?: {
    createdAt?: string;
    updatedAt?: string;
    sourcesVerified?: boolean;
  };
}
