/**
 * US holidays and observances (America-first). Used for:
 * - Theme suggestions in menu builder and activity calendar
 * - "Upcoming" nudges: "St. Patrick's Day is next week—use the theme?"
 * - Activity director calendar (one place for big + little + music + fan culture)
 *
 * Calendar reference: 2026+. All "upcoming" and theme suggestions are forward-looking.
 * We do not suggest or celebrate past holidays; we only show the next ones coming up.
 *
 * TRUST & ACCURACY: Every date is cross-referenced and verified (National Day Calendar,
 * National Today, and/or two+ independent sources). We aim for a full, aggregate calendar:
 * multiple observances per day where they exist, so event hosts see the full picture.
 * @see docs/OBSERVANCES-SOURCES-AND-VERIFICATION.md
 *
 * Categories: federal | cultural | food | music | fun | fan_culture
 * @see docs/MENU-AND-THEMING-VISION.md
 */

const CATEGORIES = Object.freeze({
  FEDERAL: "federal",
  CULTURAL: "cultural",
  FOOD: "food",
  MUSIC: "music",
  FUN: "fun",
  FAN_CULTURE: "fan_culture",
});

/** Fixed date: { name, month (1-12), day, category, themeId? } */
const FIXED = [
  // Federal & major
  { name: "New Year's Day", month: 1, day: 1, category: CATEGORIES.FEDERAL, themeId: "newyear" },
  { name: "Valentine's Day", month: 2, day: 14, category: CATEGORIES.CULTURAL, themeId: "valentines" },
  { name: "St. Patrick's Day", month: 3, day: 17, category: CATEGORIES.CULTURAL, themeId: "stpatricks" },
  { name: "Juneteenth", month: 6, day: 19, category: CATEGORIES.FEDERAL, themeId: "juneteenth" },
  { name: "Independence Day", month: 7, day: 4, category: CATEGORIES.FEDERAL, themeId: "july4" },
  { name: "Halloween", month: 10, day: 31, category: CATEGORIES.CULTURAL, themeId: "halloween" },
  { name: "Veterans Day", month: 11, day: 11, category: CATEGORIES.FEDERAL, themeId: "veterans" },
  { name: "Christmas Eve", month: 12, day: 24, category: CATEGORIES.CULTURAL, themeId: "christmas" },
  { name: "Christmas Day", month: 12, day: 25, category: CATEGORIES.FEDERAL, themeId: "christmas" },
  { name: "New Year's Eve", month: 12, day: 31, category: CATEGORIES.CULTURAL, themeId: "newyear" },
  // Music — musicians' birthdays and death anniversaries (large followings)
  { name: "Elvis Presley's birthday", month: 1, day: 8, category: CATEGORIES.MUSIC },
  { name: "David Bowie's birthday", month: 1, day: 10, category: CATEGORIES.MUSIC },
  { name: "David Bowie death anniversary", month: 1, day: 10, category: CATEGORIES.MUSIC },
  { name: "Janis Joplin's birthday", month: 1, day: 19, category: CATEGORIES.MUSIC },
  { name: "Kurt Cobain death anniversary", month: 4, day: 5, category: CATEGORIES.MUSIC },
  { name: "Prince death anniversary", month: 4, day: 21, category: CATEGORIES.MUSIC },
  { name: "Bob Marley death anniversary", month: 5, day: 11, category: CATEGORIES.MUSIC },
  { name: "Prince's birthday", month: 6, day: 7, category: CATEGORIES.MUSIC },
  { name: "Jim Morrison death anniversary", month: 7, day: 3, category: CATEGORIES.MUSIC },
  { name: "Jerry Garcia's birthday (Grateful Dead)", month: 8, day: 1, category: CATEGORIES.MUSIC },
  { name: "Jerry Garcia death anniversary", month: 8, day: 9, category: CATEGORIES.MUSIC },
  { name: "Elvis Presley death anniversary", month: 8, day: 16, category: CATEGORIES.MUSIC },
  { name: "Jimi Hendrix death anniversary", month: 9, day: 18, category: CATEGORIES.MUSIC },
  { name: "Freddie Mercury's birthday", month: 9, day: 5, category: CATEGORIES.MUSIC },
  { name: "Janis Joplin death anniversary", month: 10, day: 4, category: CATEGORIES.MUSIC },
  { name: "John Lennon's birthday", month: 10, day: 9, category: CATEGORIES.MUSIC },
  { name: "Freddie Mercury death anniversary", month: 11, day: 24, category: CATEGORIES.MUSIC },
  { name: "Jimi Hendrix's birthday", month: 11, day: 27, category: CATEGORIES.MUSIC },
  { name: "John Lennon death anniversary", month: 12, day: 8, category: CATEGORIES.MUSIC },
  { name: "Jim Morrison's birthday", month: 12, day: 8, category: CATEGORIES.MUSIC },
  // Fan culture & geek (others in deep block below)
  { name: "National Science Fiction Day", month: 1, day: 2, category: CATEGORIES.FAN_CULTURE },
  // Food & drink (additional; more in deep block below)
  { name: "National Bloody Mary Day", month: 1, day: 1, category: CATEGORIES.FOOD },
  { name: "National Spaghetti Day", month: 1, day: 2, category: CATEGORIES.FOOD },
  { name: "National Pie Day", month: 1, day: 23, category: CATEGORIES.FUN },
  // ——— Deep / unique theme-worthy observances (activity directors: "what's coming up?") ———
  // January: New year, storytelling, creativity, hot tea, soup
  { name: "National Trivia Day", month: 1, day: 4, category: CATEGORIES.FUN },
  { name: "National Bird Day", month: 1, day: 5, category: CATEGORIES.FUN },
  { name: "National Bean Day", month: 1, day: 6, category: CATEGORIES.FOOD },
  { name: "National Tempura Day", month: 1, day: 7, category: CATEGORIES.FOOD },
  { name: "National Bubble Bath Day", month: 1, day: 8, category: CATEGORIES.FUN },
  { name: "National Apricot Day", month: 1, day: 9, category: CATEGORIES.FOOD },
  { name: "National Houseplant Appreciation Day", month: 1, day: 10, category: CATEGORIES.FUN },
  { name: "National Milk Day", month: 1, day: 11, category: CATEGORIES.FOOD },
  { name: "National Hot Tea Day", month: 1, day: 12, category: CATEGORIES.FOOD },
  { name: "National Rubber Ducky Day", month: 1, day: 13, category: CATEGORIES.FUN },
  { name: "National Dress Up Your Pet Day", month: 1, day: 14, category: CATEGORIES.FUN },
  { name: "National Hat Day", month: 1, day: 15, category: CATEGORIES.FUN },
  { name: "National Nothing Day", month: 1, day: 16, category: CATEGORIES.FUN },
  { name: "National Bootlegger's Day", month: 1, day: 17, category: CATEGORIES.FUN },
  { name: "National Winnie the Pooh Day", month: 1, day: 18, category: CATEGORIES.FAN_CULTURE },
  { name: "National Popcorn Day", month: 1, day: 19, category: CATEGORIES.FOOD },
  { name: "National Cheese Lover's Day", month: 1, day: 20, category: CATEGORIES.FOOD },
  { name: "National Hugging Day", month: 1, day: 21, category: CATEGORIES.FUN },
  { name: "National Blonde Brownie Day", month: 1, day: 22, category: CATEGORIES.FOOD },
  { name: "National Handwriting Day", month: 1, day: 23, category: CATEGORIES.FUN },
  { name: "National Peanut Butter Day", month: 1, day: 24, category: CATEGORIES.FOOD },
  { name: "National Beer Can Appreciation Day", month: 1, day: 24, category: CATEGORIES.FOOD },
  { name: "National Compliment Day", month: 1, day: 24, category: CATEGORIES.FUN },
  { name: "National Irish Coffee Day", month: 1, day: 25, category: CATEGORIES.FOOD },
  { name: "National Peanut Brittle Day", month: 1, day: 26, category: CATEGORIES.FOOD },
  { name: "National Chocolate Cake Day", month: 1, day: 27, category: CATEGORIES.FOOD },
  { name: "National Kazoo Day", month: 1, day: 28, category: CATEGORIES.MUSIC },
  { name: "National Puzzle Day", month: 1, day: 29, category: CATEGORIES.FUN },
  { name: "National Croissant Day", month: 1, day: 30, category: CATEGORIES.FOOD },
  // February: love, kindness, Black History Month start, storytelling (cross-ref: National Day Calendar, National Today)
  { name: "Black History Month begins", month: 2, day: 1, category: CATEGORIES.CULTURAL },
  { name: "National Dark Chocolate Day", month: 2, day: 1, category: CATEGORIES.FOOD },
  { name: "National Get Up Day", month: 2, day: 1, category: CATEGORIES.FUN },
  { name: "Groundhog Day", month: 2, day: 2, category: CATEGORIES.CULTURAL },
  { name: "National Wear Red Day", month: 2, day: 2, category: CATEGORIES.CULTURAL },
  { name: "National Carrot Cake Day", month: 2, day: 3, category: CATEGORIES.FOOD },
  { name: "National Women Physicians Day", month: 2, day: 3, category: CATEGORIES.CULTURAL },
  { name: "National Homemade Soup Day", month: 2, day: 4, category: CATEGORIES.FOOD },
  { name: "National Hemp Day", month: 2, day: 4, category: CATEGORIES.FUN },
  { name: "National Weatherperson's Day", month: 2, day: 5, category: CATEGORIES.FUN },
  { name: "National Frozen Yogurt Day", month: 2, day: 6, category: CATEGORIES.FOOD },
  { name: "National Send a Card to a Friend Day", month: 2, day: 7, category: CATEGORIES.FUN },
  { name: "National Kite Flying Day", month: 2, day: 8, category: CATEGORIES.FUN },
  { name: "National Pizza Day", month: 2, day: 9, category: CATEGORIES.FOOD },
  { name: "National Cut the Cord Day", month: 2, day: 9, category: CATEGORIES.FUN },
  { name: "National Umbrella Day", month: 2, day: 10, category: CATEGORIES.FUN },
  { name: "National Make a Friend Day", month: 2, day: 11, category: CATEGORIES.FUN },
  { name: "Lincoln's Birthday", month: 2, day: 12, category: CATEGORIES.CULTURAL },
  { name: "National Plum Pudding Day", month: 2, day: 12, category: CATEGORIES.FOOD },
  { name: "National Galentine's Day", month: 2, day: 13, category: CATEGORIES.CULTURAL },
  { name: "National Cheddar Day", month: 2, day: 13, category: CATEGORIES.FOOD },
  { name: "National Ferris Wheel Day", month: 2, day: 14, category: CATEGORIES.FUN },
  { name: "National Gumdrop Day", month: 2, day: 15, category: CATEGORIES.FOOD },
  { name: "National Almond Day", month: 2, day: 16, category: CATEGORIES.FOOD },
  { name: "National Random Acts of Kindness Day", month: 2, day: 17, category: CATEGORIES.FUN },
  { name: "National Drink Wine Day", month: 2, day: 18, category: CATEGORIES.FOOD },
  { name: "National Chocolate Mint Day", month: 2, day: 19, category: CATEGORIES.FOOD },
  { name: "National Lash Day", month: 2, day: 19, category: CATEGORIES.FUN },
  { name: "National Love Your Pet Day", month: 2, day: 20, category: CATEGORIES.FUN },
  { name: "National Comfy Day", month: 2, day: 20, category: CATEGORIES.FUN },
  { name: "National Leadership Day", month: 2, day: 20, category: CATEGORIES.FUN },
  { name: "National Boiled Peanuts Day", month: 2, day: 21, category: CATEGORIES.FOOD },
  { name: "National Grain-Free Day", month: 2, day: 21, category: CATEGORIES.FOOD },
  { name: "National Margarita Day", month: 2, day: 22, category: CATEGORIES.FOOD },
  { name: "National Chili Day", month: 2, day: 22, category: CATEGORIES.FOOD },
  { name: "National Supermarket Employee Day", month: 2, day: 22, category: CATEGORIES.FUN },
  { name: "National Banana Bread Day", month: 2, day: 23, category: CATEGORIES.FOOD },
  { name: "National Tile Day", month: 2, day: 23, category: CATEGORIES.FUN },
  { name: "National Tell a Fairy Tale Day", month: 2, day: 26, category: CATEGORIES.FUN },
  { name: "National Strawberry Day", month: 2, day: 27, category: CATEGORIES.FOOD },
  { name: "National Kahlúa Day", month: 2, day: 27, category: CATEGORIES.FOOD },
  { name: "Pokémon Day", month: 2, day: 27, category: CATEGORIES.FAN_CULTURE },
  { name: "National Retro Day", month: 2, day: 27, category: CATEGORIES.FUN },
  { name: "National Tooth Fairy Day", month: 2, day: 28, category: CATEGORIES.FUN },
  // March: St. Patrick's, spring, reading, wildlife, crafts (cross-ref: NDC, National Today)
  { name: "National Peanut Butter Lover's Day", month: 3, day: 1, category: CATEGORIES.FOOD },
  { name: "National Pig Day", month: 3, day: 1, category: CATEGORIES.FUN },
  { name: "National Fruit Compote Day", month: 3, day: 1, category: CATEGORIES.FOOD },
  { name: "National Minnesota Day", month: 3, day: 1, category: CATEGORIES.CULTURAL },
  { name: "National Read Across America Day", month: 3, day: 2, category: CATEGORIES.CULTURAL },
  { name: "National Dr. Seuss Day", month: 3, day: 2, category: CATEGORIES.FAN_CULTURE },
  { name: "National Banana Cream Pie Day", month: 3, day: 2, category: CATEGORIES.FOOD },
  { name: "National Old Stuff Day", month: 3, day: 2, category: CATEGORIES.FUN },
  { name: "National Anthem Day", month: 3, day: 3, category: CATEGORIES.CULTURAL },
  { name: "National Soup It Forward Day", month: 3, day: 3, category: CATEGORIES.FOOD },
  { name: "National Mulled Wine Day", month: 3, day: 3, category: CATEGORIES.FOOD },
  { name: "National Cold Cuts Day", month: 3, day: 3, category: CATEGORIES.FOOD },
  { name: "National I Want You to Be Happy Day", month: 3, day: 3, category: CATEGORIES.FUN },
  { name: "National Grammar Day", month: 3, day: 4, category: CATEGORIES.FUN },
  { name: "National Sons Day", month: 3, day: 4, category: CATEGORIES.CULTURAL },
  { name: "Marching Music Day", month: 3, day: 4, category: CATEGORIES.MUSIC },
  { name: "National Hug a G.I. Day", month: 3, day: 4, category: CATEGORIES.CULTURAL },
  { name: "National Pound Cake Day", month: 3, day: 4, category: CATEGORIES.FOOD },
  { name: "National Cheese Doodle Day", month: 3, day: 5, category: CATEGORIES.FOOD },
  { name: "National Absinthe Day", month: 3, day: 5, category: CATEGORIES.FOOD },
  { name: "National Multiple Personality Day", month: 3, day: 5, category: CATEGORIES.FUN },
  { name: "National Oreo Cookie Day", month: 3, day: 6, category: CATEGORIES.FOOD },
  { name: "National White Chocolate Cheesecake Day", month: 3, day: 6, category: CATEGORIES.FOOD },
  { name: "National Frozen Food Day", month: 3, day: 6, category: CATEGORIES.FOOD },
  { name: "National Dentist's Day", month: 3, day: 6, category: CATEGORIES.FUN },
  { name: "National Dress Day", month: 3, day: 6, category: CATEGORIES.FUN },
  { name: "National Cereal Day", month: 3, day: 7, category: CATEGORIES.FOOD },
  { name: "National Flapjack Day", month: 3, day: 7, category: CATEGORIES.FOOD },
  { name: "National Crown Roast of Pork Day", month: 3, day: 7, category: CATEGORIES.FOOD },
  { name: "National Be Heard Day", month: 3, day: 7, category: CATEGORIES.FUN },
  { name: "National Proofreading Day", month: 3, day: 8, category: CATEGORIES.FUN },
  { name: "National Oregon Day", month: 3, day: 8, category: CATEGORIES.CULTURAL },
  { name: "National Barbie Day", month: 3, day: 9, category: CATEGORIES.FUN },
  { name: "National Mario Day", month: 3, day: 10, category: CATEGORIES.FAN_CULTURE },
  { name: "National Johnny Appleseed Day", month: 3, day: 11, category: CATEGORIES.CULTURAL },
  { name: "National Plant a Flower Day", month: 3, day: 12, category: CATEGORIES.FUN },
  { name: "National Napping Day", month: 3, day: 13, category: CATEGORIES.FUN },
  { name: "National Pi Day", month: 3, day: 14, category: CATEGORIES.FUN },
  { name: "National Everything You Think Is Wrong Day", month: 3, day: 15, category: CATEGORIES.FUN },
  { name: "National Panda Day", month: 3, day: 16, category: CATEGORIES.FUN },
  { name: "National Corned Beef and Cabbage Day", month: 3, day: 17, category: CATEGORIES.FOOD },
  { name: "National Sloppy Joe Day", month: 3, day: 18, category: CATEGORIES.FOOD },
  { name: "National Let's Laugh Day", month: 3, day: 19, category: CATEGORIES.FUN },
  { name: "National Proposal Day", month: 3, day: 20, category: CATEGORIES.FUN },
  { name: "National French Bread Day", month: 3, day: 21, category: CATEGORIES.FOOD },
  { name: "National Goof Off Day", month: 3, day: 22, category: CATEGORIES.FUN },
  { name: "National Puppy Day", month: 3, day: 23, category: CATEGORIES.FUN },
  { name: "National Cheesesteak Day", month: 3, day: 24, category: CATEGORIES.FOOD },
  { name: "National Tolkien Reading Day", month: 3, day: 25, category: CATEGORIES.FAN_CULTURE },
  { name: "National Spinach Day", month: 3, day: 26, category: CATEGORIES.FOOD },
  { name: "National Spanish Paella Day", month: 3, day: 27, category: CATEGORIES.FOOD },
  { name: "International Whiskey Day", month: 3, day: 27, category: CATEGORIES.FOOD },
  { name: "National Something on a Stick Day", month: 3, day: 28, category: CATEGORIES.FUN },
  { name: "National Mom and Pop Business Day", month: 3, day: 29, category: CATEGORIES.FUN },
  { name: "National Pencil Day", month: 3, day: 30, category: CATEGORIES.FUN },
  { name: "National Crayon Day", month: 3, day: 31, category: CATEGORIES.FUN },
  // April: Easter, Earth, books, beer, jazz (cross-ref: NDC, National Today)
  { name: "National April Fools' Day", month: 4, day: 1, category: CATEGORIES.FUN },
  { name: "National Peanut Butter and Jelly Day", month: 4, day: 2, category: CATEGORIES.FOOD },
  { name: "World Autism Awareness Day", month: 4, day: 2, category: CATEGORIES.CULTURAL },
  { name: "National Find a Rainbow Day", month: 4, day: 3, category: CATEGORIES.FUN },
  { name: "National Walk to Work Day", month: 4, day: 4, category: CATEGORIES.FUN },
  { name: "International Carrot Day", month: 4, day: 4, category: CATEGORIES.FOOD },
  { name: "National Caramel Day", month: 4, day: 5, category: CATEGORIES.FOOD },
  { name: "National Tartan Day", month: 4, day: 6, category: CATEGORIES.CULTURAL },
  { name: "National Beer Day", month: 4, day: 7, category: CATEGORIES.FOOD },
  { name: "World Health Day", month: 4, day: 7, category: CATEGORIES.CULTURAL },
  { name: "National Empanada Day", month: 4, day: 8, category: CATEGORIES.FOOD },
  { name: "National Unicorn Day", month: 4, day: 9, category: CATEGORIES.FUN },
  { name: "National Siblings Day", month: 4, day: 10, category: CATEGORIES.CULTURAL },
  { name: "National Pet Day", month: 4, day: 11, category: CATEGORIES.FUN },
  { name: "National Grilled Cheese Day", month: 4, day: 12, category: CATEGORIES.FOOD },
  { name: "National Scrabble Day", month: 4, day: 13, category: CATEGORIES.FUN },
  { name: "National Dolphin Day", month: 4, day: 14, category: CATEGORIES.FUN },
  { name: "National Titanic Remembrance Day", month: 4, day: 15, category: CATEGORIES.CULTURAL },
  { name: "National Stress Awareness Day", month: 4, day: 16, category: CATEGORIES.FUN },
  { name: "National Haiku Poetry Day", month: 4, day: 17, category: CATEGORIES.FUN },
  { name: "National Animal Crackers Day", month: 4, day: 18, category: CATEGORIES.FOOD },
  { name: "National Garlic Day", month: 4, day: 19, category: CATEGORIES.FOOD },
  { name: "National Lima Bean Respect Day", month: 4, day: 20, category: CATEGORIES.FOOD },
  { name: "National Tea Day", month: 4, day: 21, category: CATEGORIES.FOOD },
  { name: "National Earth Day", month: 4, day: 22, category: CATEGORIES.CULTURAL },
  { name: "National Picnic Day", month: 4, day: 23, category: CATEGORIES.FUN },
  { name: "National Pigs in a Blanket Day", month: 4, day: 24, category: CATEGORIES.FOOD },
  { name: "National DNA Day", month: 4, day: 25, category: CATEGORIES.FUN },
  { name: "National Pretzel Day", month: 4, day: 26, category: CATEGORIES.FOOD },
  { name: "National Tell a Story Day", month: 4, day: 27, category: CATEGORIES.FUN },
  { name: "National Superhero Day", month: 4, day: 28, category: CATEGORIES.FAN_CULTURE },
  { name: "National Zipper Day", month: 4, day: 29, category: CATEGORIES.FUN },
  { name: "National Jazz Day", month: 4, day: 30, category: CATEGORIES.MUSIC },
  // May: Star Wars, mothers, tacos, wine, memorial (cross-ref: NDC, National Today)
  { name: "National Chocolate Parfait Day", month: 5, day: 1, category: CATEGORIES.FOOD },
  { name: "National Truffle Day", month: 5, day: 2, category: CATEGORIES.FOOD },
  { name: "National Two Different Colored Shoes Day", month: 5, day: 3, category: CATEGORIES.FUN },
  { name: "Star Wars Day (May the 4th)", month: 5, day: 4, category: CATEGORIES.FAN_CULTURE },
  { name: "National Cinco de Mayo", month: 5, day: 5, category: CATEGORIES.CULTURAL },
  { name: "National Beverage Day", month: 5, day: 6, category: CATEGORIES.FOOD },
  { name: "National Nurses Day", month: 5, day: 6, category: CATEGORIES.CULTURAL },
  { name: "National Cosmopolitan Day", month: 5, day: 7, category: CATEGORIES.FOOD },
  { name: "National Coconut Cream Pie Day", month: 5, day: 8, category: CATEGORIES.FOOD },
  { name: "National Lost Sock Memorial Day", month: 5, day: 9, category: CATEGORIES.FUN },
  { name: "National Clean Up Your Room Day", month: 5, day: 10, category: CATEGORIES.FUN },
  { name: "National Eat What You Want Day", month: 5, day: 11, category: CATEGORIES.FOOD },
  { name: "National Limerick Day", month: 5, day: 12, category: CATEGORIES.FUN },
  { name: "National Frog Jumping Day", month: 5, day: 13, category: CATEGORIES.FUN },
  { name: "National Hummus Day", month: 5, day: 13, category: CATEGORIES.FOOD },
  { name: "National Buttermilk Biscuit Day", month: 5, day: 14, category: CATEGORIES.FOOD },
  { name: "National Chocolate Chip Day", month: 5, day: 15, category: CATEGORIES.FOOD },
  { name: "National Do Something Good for Your Neighbor Day", month: 5, day: 16, category: CATEGORIES.FUN },
  { name: "National Pack Your Lunch Day", month: 5, day: 17, category: CATEGORIES.FUN },
  { name: "National Visit Your Relatives Day", month: 5, day: 18, category: CATEGORIES.FUN },
  { name: "National May Ray Day", month: 5, day: 19, category: CATEGORIES.FUN },
  { name: "National Be a Millionaire Day", month: 5, day: 20, category: CATEGORIES.FUN },
  { name: "National Strawberries and Cream Day", month: 5, day: 21, category: CATEGORIES.FOOD },
  { name: "National Maritime Day", month: 5, day: 22, category: CATEGORIES.CULTURAL },
  { name: "National Taffy Day", month: 5, day: 23, category: CATEGORIES.FOOD },
  { name: "National Scavenger Hunt Day", month: 5, day: 24, category: CATEGORIES.FUN },
  { name: "Towel Day (Hitchhiker's Guide)", month: 5, day: 25, category: CATEGORIES.FAN_CULTURE },
  { name: "National Wine Day", month: 5, day: 25, category: CATEGORIES.FOOD },
  { name: "National Paper Airplane Day", month: 5, day: 26, category: CATEGORIES.FUN },
  { name: "National Grape Popsicle Day", month: 5, day: 27, category: CATEGORIES.FOOD },
  { name: "National Hamburger Day", month: 5, day: 28, category: CATEGORIES.FOOD },
  { name: "National Coq Au Vin Day", month: 5, day: 29, category: CATEGORIES.FOOD },
  { name: "National Mint Julep Day", month: 5, day: 30, category: CATEGORIES.FOOD },
  { name: "National Macaroon Day", month: 5, day: 31, category: CATEGORIES.FOOD },
  // June: Doughnut, Father's, summer, Pride (cross-ref: NDC, National Today)
  { name: "National Olive Day", month: 6, day: 1, category: CATEGORIES.FOOD },
  { name: "National Rocky Road Day", month: 6, day: 2, category: CATEGORIES.FOOD },
  { name: "National Egg Day", month: 6, day: 3, category: CATEGORIES.FOOD },
  { name: "National Cheese Day", month: 6, day: 4, category: CATEGORIES.FOOD },
  { name: "National Gingerbread Day", month: 6, day: 5, category: CATEGORIES.FOOD },
  { name: "National Yo-Yo Day", month: 6, day: 6, category: CATEGORIES.FUN },
  { name: "National Chocolate Ice Cream Day", month: 6, day: 7, category: CATEGORIES.FOOD },
  { name: "National Best Friends Day", month: 6, day: 8, category: CATEGORIES.FUN },
  { name: "National Strawberry Rhubarb Pie Day", month: 6, day: 9, category: CATEGORIES.FOOD },
  { name: "National Iced Tea Day", month: 6, day: 10, category: CATEGORIES.FOOD },
  { name: "National German Chocolate Cake Day", month: 6, day: 11, category: CATEGORIES.FOOD },
  { name: "National Corn on the Cob Day", month: 6, day: 11, category: CATEGORIES.FOOD },
  { name: "National Peanut Butter Cookie Day", month: 6, day: 12, category: CATEGORIES.FOOD },
  { name: "National Sewing Machine Day", month: 6, day: 13, category: CATEGORIES.FUN },
  { name: "National Bourbon Day", month: 6, day: 14, category: CATEGORIES.FOOD },
  { name: "National Smile Power Day", month: 6, day: 15, category: CATEGORIES.FUN },
  { name: "National Fudge Day", month: 6, day: 16, category: CATEGORIES.FOOD },
  { name: "National Eat Your Vegetables Day", month: 6, day: 17, category: CATEGORIES.FOOD },
  { name: "National Go Fishing Day", month: 6, day: 18, category: CATEGORIES.FUN },
  { name: "Juneteenth", month: 6, day: 19, category: CATEGORIES.FEDERAL },
  { name: "National Ice Cream Soda Day", month: 6, day: 20, category: CATEGORIES.FOOD },
  { name: "National Peaches and Cream Day", month: 6, day: 21, category: CATEGORIES.FOOD },
  { name: "National Onion Rings Day", month: 6, day: 22, category: CATEGORIES.FOOD },
  { name: "National Pink Day", month: 6, day: 23, category: CATEGORIES.FUN },
  { name: "National Pralines Day", month: 6, day: 24, category: CATEGORIES.FOOD },
  { name: "National Catfish Day", month: 6, day: 25, category: CATEGORIES.FOOD },
  { name: "National Coconut Day", month: 6, day: 26, category: CATEGORIES.FOOD },
  { name: "National Sunglasses Day", month: 6, day: 27, category: CATEGORIES.FUN },
  { name: "National Tapioca Day", month: 6, day: 28, category: CATEGORIES.FOOD },
  { name: "National Camera Day", month: 6, day: 29, category: CATEGORIES.FUN },
  { name: "National Social Media Day", month: 6, day: 30, category: CATEGORIES.FUN },
  // July: Independence, fireworks, summer, ice cream (cross-ref: NDC, National Today)
  { name: "National Gingersnap Day", month: 7, day: 1, category: CATEGORIES.FOOD },
  { name: "National Anisette Day", month: 7, day: 2, category: CATEGORIES.FOOD },
  { name: "National Fried Clam Day", month: 7, day: 3, category: CATEGORIES.FOOD },
  { name: "National Barbecued Spareribs Day", month: 7, day: 4, category: CATEGORIES.FOOD },
  { name: "Independence Day", month: 7, day: 4, category: CATEGORIES.FEDERAL },
  { name: "National Apple Turnover Day", month: 7, day: 5, category: CATEGORIES.FOOD },
  { name: "National Fried Chicken Day", month: 7, day: 6, category: CATEGORIES.FOOD },
  { name: "National Macaroni Day", month: 7, day: 7, category: CATEGORIES.FOOD },
  { name: "National Milk Chocolate with Almonds Day", month: 7, day: 8, category: CATEGORIES.FOOD },
  { name: "National Sugar Cookie Day", month: 7, day: 9, category: CATEGORIES.FOOD },
  { name: "National Pina Colada Day", month: 7, day: 10, category: CATEGORIES.FOOD },
  { name: "National Blueberry Muffin Day", month: 7, day: 11, category: CATEGORIES.FOOD },
  { name: "National Pecan Pie Day", month: 7, day: 12, category: CATEGORIES.FOOD },
  { name: "National French Fry Day", month: 7, day: 13, category: CATEGORIES.FOOD },
  { name: "National Nude Day", month: 7, day: 14, category: CATEGORIES.FUN },
  { name: "National Tapioca Pudding Day", month: 7, day: 15, category: CATEGORIES.FOOD },
  { name: "National Corn Fritters Day", month: 7, day: 16, category: CATEGORIES.FOOD },
  { name: "National Peach Ice Cream Day", month: 7, day: 17, category: CATEGORIES.FOOD },
  { name: "National Caviar Day", month: 7, day: 18, category: CATEGORIES.FOOD },
  { name: "National Daiquiri Day", month: 7, day: 19, category: CATEGORIES.FOOD },
  { name: "National Lollipop Day", month: 7, day: 20, category: CATEGORIES.FOOD },
  { name: "National Junk Food Day", month: 7, day: 21, category: CATEGORIES.FOOD },
  { name: "National Hammock Day", month: 7, day: 22, category: CATEGORIES.FUN },
  { name: "National Vanilla Ice Cream Day", month: 7, day: 23, category: CATEGORIES.FOOD },
  { name: "National Tequila Day", month: 7, day: 24, category: CATEGORIES.FOOD },
  { name: "National Hot Fudge Sundae Day", month: 7, day: 25, category: CATEGORIES.FOOD },
  { name: "National Coffee Milkshake Day", month: 7, day: 26, category: CATEGORIES.FOOD },
  { name: "National Scotch Day", month: 7, day: 27, category: CATEGORIES.FOOD },
  { name: "National Milk Chocolate Day", month: 7, day: 28, category: CATEGORIES.FOOD },
  { name: "National Lasagna Day", month: 7, day: 29, category: CATEGORIES.FOOD },
  { name: "National Cheesecake Day", month: 7, day: 30, category: CATEGORIES.FOOD },
  { name: "National Avocado Day", month: 7, day: 31, category: CATEGORIES.FOOD },
  // August: summer, dog, left-handers, book lovers (cross-ref: NDC, National Today)
  { name: "National Raspberry Cream Pie Day", month: 8, day: 1, category: CATEGORIES.FOOD },
  { name: "National Ice Cream Sandwich Day", month: 8, day: 2, category: CATEGORIES.FOOD },
  { name: "National Watermelon Day", month: 8, day: 3, category: CATEGORIES.FOOD },
  { name: "National Chocolate Chip Cookie Day", month: 8, day: 4, category: CATEGORIES.FOOD },
  { name: "National Oyster Day", month: 8, day: 5, category: CATEGORIES.FOOD },
  { name: "National Root Beer Float Day", month: 8, day: 6, category: CATEGORIES.FOOD },
  { name: "National Lighthouse Day", month: 8, day: 7, category: CATEGORIES.FUN },
  { name: "National Happiness Happens Day", month: 8, day: 8, category: CATEGORIES.FUN },
  { name: "National Book Lovers Day", month: 8, day: 9, category: CATEGORIES.FUN },
  { name: "National S'mores Day", month: 8, day: 10, category: CATEGORIES.FOOD },
  { name: "National Son and Daughter Day", month: 8, day: 11, category: CATEGORIES.FUN },
  { name: "National Middle Child Day", month: 8, day: 12, category: CATEGORIES.FUN },
  { name: "National Left-Handers Day", month: 8, day: 13, category: CATEGORIES.FUN },
  { name: "National Creamsicle Day", month: 8, day: 14, category: CATEGORIES.FOOD },
  { name: "National Relaxation Day", month: 8, day: 15, category: CATEGORIES.FUN },
  { name: "National Roller Coaster Day", month: 8, day: 16, category: CATEGORIES.FUN },
  { name: "National Thrift Shop Day", month: 8, day: 17, category: CATEGORIES.FUN },
  { name: "National Ice Cream Pie Day", month: 8, day: 18, category: CATEGORIES.FOOD },
  { name: "National Aviation Day", month: 8, day: 19, category: CATEGORIES.FUN },
  { name: "National Chocolate Pecan Pie Day", month: 8, day: 20, category: CATEGORIES.FOOD },
  { name: "National Senior Citizens Day", month: 8, day: 21, category: CATEGORIES.CULTURAL },
  { name: "National Spumoni Day", month: 8, day: 21, category: CATEGORIES.FOOD },
  { name: "National Be an Angel Day", month: 8, day: 22, category: CATEGORIES.FUN },
  { name: "National Sponge Cake Day", month: 8, day: 23, category: CATEGORIES.FOOD },
  { name: "National Waffle Day", month: 8, day: 24, category: CATEGORIES.FOOD },
  { name: "National Banana Split Day", month: 8, day: 25, category: CATEGORIES.FOOD },
  { name: "National Dog Day", month: 8, day: 26, category: CATEGORIES.FUN },
  { name: "National Banana Lovers Day", month: 8, day: 27, category: CATEGORIES.FOOD },
  { name: "National Red Wine Day", month: 8, day: 28, category: CATEGORIES.FOOD },
  { name: "National Lemon Juice Day", month: 8, day: 29, category: CATEGORIES.FOOD },
  { name: "National Toasted Marshmallow Day", month: 8, day: 30, category: CATEGORIES.FOOD },
  { name: "National Trail Mix Day", month: 8, day: 31, category: CATEGORIES.FOOD },
  // September: back to school, grandparents, coffee, fall (cross-ref: NDC, National Today)
  { name: "National Cherry Popover Day", month: 9, day: 1, category: CATEGORIES.FOOD },
  { name: "National Blueberry Popsicle Day", month: 9, day: 2, category: CATEGORIES.FOOD },
  { name: "National Welsh Rarebit Day", month: 9, day: 3, category: CATEGORIES.FOOD },
  { name: "National Wildlife Day", month: 9, day: 4, category: CATEGORIES.FUN },
  { name: "National Cheese Pizza Day", month: 9, day: 5, category: CATEGORIES.FOOD },
  { name: "National Read a Book Day", month: 9, day: 6, category: CATEGORIES.FUN },
  { name: "National Beer Lover's Day", month: 9, day: 7, category: CATEGORIES.FOOD },
  { name: "National Star Trek Day", month: 9, day: 8, category: CATEGORIES.FAN_CULTURE },
  { name: "National Teddy Bear Day", month: 9, day: 9, category: CATEGORIES.FUN },
  { name: "National Swap Ideas Day", month: 9, day: 10, category: CATEGORIES.FUN },
  { name: "National Make Your Bed Day", month: 9, day: 11, category: CATEGORIES.FUN },
  { name: "National Video Games Day", month: 9, day: 12, category: CATEGORIES.FAN_CULTURE },
  { name: "National Cream Filled Donut Day", month: 9, day: 14, category: CATEGORIES.FOOD },
  { name: "Hispanic Heritage Month begins", month: 9, day: 15, category: CATEGORIES.CULTURAL },
  { name: "National Double Cheeseburger Day", month: 9, day: 15, category: CATEGORIES.FOOD },
  { name: "National Guacamole Day", month: 9, day: 16, category: CATEGORIES.FOOD },
  { name: "National Apple Dumpling Day", month: 9, day: 17, category: CATEGORIES.FOOD },
  { name: "National Cheeseburger Day", month: 9, day: 18, category: CATEGORIES.FOOD },
  { name: "Talk Like a Pirate Day", month: 9, day: 19, category: CATEGORIES.FAN_CULTURE },
  { name: "National Punch Day", month: 9, day: 20, category: CATEGORIES.FOOD },
  { name: "National Pecan Cookie Day", month: 9, day: 21, category: CATEGORIES.FOOD },
  { name: "National Ice Cream Cone Day", month: 9, day: 22, category: CATEGORIES.FOOD },
  { name: "National Checkers Day", month: 9, day: 23, category: CATEGORIES.FUN },
  { name: "National Punctuation Day", month: 9, day: 24, category: CATEGORIES.FUN },
  { name: "National Comic Book Day", month: 9, day: 25, category: CATEGORIES.FAN_CULTURE },
  { name: "National Pancake Day", month: 9, day: 26, category: CATEGORIES.FOOD },
  { name: "National Chocolate Milk Day", month: 9, day: 27, category: CATEGORIES.FOOD },
  { name: "National Good Neighbor Day", month: 9, day: 28, category: CATEGORIES.FUN },
  { name: "National Coffee Day", month: 9, day: 29, category: CATEGORIES.FOOD },
  { name: "National Hot Mulled Cider Day", month: 9, day: 30, category: CATEGORIES.FOOD },
  // October: Halloween, fall, pasta, pizza (cross-ref: NDC, National Today)
  { name: "National Homemade Cookies Day", month: 10, day: 1, category: CATEGORIES.FOOD },
  { name: "National Name Your Car Day", month: 10, day: 2, category: CATEGORIES.FUN },
  { name: "National Caramel Custard Day", month: 10, day: 3, category: CATEGORIES.FOOD },
  { name: "National Do Something Nice Day", month: 10, day: 5, category: CATEGORIES.FUN },
  { name: "National Noodle Day", month: 10, day: 6, category: CATEGORIES.FOOD },
  { name: "National Frappe Day", month: 10, day: 7, category: CATEGORIES.FOOD },
  { name: "National Pierogi Day", month: 10, day: 8, category: CATEGORIES.FUN },
  { name: "National Moldy Cheese Day", month: 10, day: 9, category: CATEGORIES.FOOD },
  { name: "National Cake Decorating Day", month: 10, day: 10, category: CATEGORIES.FUN },
  { name: "World Mental Health Day", month: 10, day: 10, category: CATEGORIES.CULTURAL },
  { name: "National Sausage Pizza Day", month: 10, day: 11, category: CATEGORIES.FOOD },
  { name: "National Fossil Day", month: 10, day: 12, category: CATEGORIES.FUN },
  { name: "National Train Your Brain Day", month: 10, day: 13, category: CATEGORIES.FUN },
  { name: "National Dessert Day", month: 10, day: 14, category: CATEGORIES.FOOD },
  { name: "National Grouch Day", month: 10, day: 15, category: CATEGORIES.FUN },
  { name: "National Dictionary Day", month: 10, day: 16, category: CATEGORIES.FUN },
  { name: "National Pasta Day", month: 10, day: 17, category: CATEGORIES.FUN },
  { name: "National Chocolate Cupcake Day", month: 10, day: 18, category: CATEGORIES.FOOD },
  { name: "National Evaluate Your Life Day", month: 10, day: 19, category: CATEGORIES.FUN },
  { name: "National Brandied Fruit Day", month: 10, day: 20, category: CATEGORIES.FOOD },
  { name: "Back to the Future Day", month: 10, day: 21, category: CATEGORIES.FAN_CULTURE },
  { name: "National Nut Day", month: 10, day: 22, category: CATEGORIES.FOOD },
  { name: "National Boston Cream Pie Day", month: 10, day: 23, category: CATEGORIES.FOOD },
  { name: "National Bologna Day", month: 10, day: 24, category: CATEGORIES.FOOD },
  { name: "National Greasy Foods Day", month: 10, day: 25, category: CATEGORIES.FOOD },
  { name: "National Pumpkin Day", month: 10, day: 26, category: CATEGORIES.FUN },
  { name: "National American Beer Day", month: 10, day: 27, category: CATEGORIES.FOOD },
  { name: "National Chocolate Day", month: 10, day: 28, category: CATEGORIES.FOOD },
  { name: "National Cat Day", month: 10, day: 29, category: CATEGORIES.FUN },
  { name: "National Candy Corn Day", month: 10, day: 30, category: CATEGORIES.FOOD },
  { name: "Halloween", month: 10, day: 31, category: CATEGORIES.CULTURAL },
  // November: Thanksgiving, veterans, turkeys, kindness (cross-ref: NDC, National Today)
  { name: "National Author's Day", month: 11, day: 1, category: CATEGORIES.FUN },
  { name: "National Deviled Egg Day", month: 11, day: 2, category: CATEGORIES.FOOD },
  { name: "National Sandwich Day", month: 11, day: 3, category: CATEGORIES.FOOD },
  { name: "National Candy Day", month: 11, day: 4, category: CATEGORIES.FOOD },
  { name: "National Donut Day (November)", month: 11, day: 5, category: CATEGORIES.FOOD },
  { name: "National Nachos Day", month: 11, day: 6, category: CATEGORIES.FOOD },
  { name: "National Bittersweet Chocolate with Almonds Day", month: 11, day: 7, category: CATEGORIES.FOOD },
  { name: "National STEM Day", month: 11, day: 8, category: CATEGORIES.FUN },
  { name: "National Scrapple Day", month: 11, day: 9, category: CATEGORIES.FOOD },
  { name: "National Vanilla Cupcake Day", month: 11, day: 10, category: CATEGORIES.FOOD },
  { name: "Veterans Day", month: 11, day: 11, category: CATEGORIES.FEDERAL },
  { name: "National Pizza with the Works Day", month: 11, day: 12, category: CATEGORIES.FOOD },
  { name: "National Kindness Day", month: 11, day: 13, category: CATEGORIES.FUN },
  { name: "National Pickle Day", month: 11, day: 14, category: CATEGORIES.FOOD },
  { name: "National Clean Out Your Refrigerator Day", month: 11, day: 15, category: CATEGORIES.FUN },
  { name: "National Fast Food Day", month: 11, day: 16, category: CATEGORIES.FOOD },
  { name: "National Baklava Day", month: 11, day: 17, category: CATEGORIES.FOOD },
  { name: "National Apple Cider Day", month: 11, day: 18, category: CATEGORIES.FOOD },
  { name: "National Play Monopoly Day", month: 11, day: 19, category: CATEGORIES.FUN },
  { name: "National Peanut Butter Fudge Day", month: 11, day: 20, category: CATEGORIES.FOOD },
  { name: "National Gingerbread Cookie Day", month: 11, day: 21, category: CATEGORIES.FOOD },
  { name: "National Cranberry Relish Day", month: 11, day: 22, category: CATEGORIES.FOOD },
  { name: "Doctor Who Day", month: 11, day: 23, category: CATEGORIES.FAN_CULTURE },
  { name: "Freddie Mercury death anniversary", month: 11, day: 24, category: CATEGORIES.MUSIC },
  { name: "National Parfait Day", month: 11, day: 25, category: CATEGORIES.FOOD },
  { name: "National Cake Day", month: 11, day: 26, category: CATEGORIES.FOOD },
  { name: "National Craft Jerky Day", month: 11, day: 27, category: CATEGORIES.FOOD },
  { name: "National French Toast Day", month: 11, day: 28, category: CATEGORIES.FOOD },
  { name: "National Lemon Cream Pie Day", month: 11, day: 29, category: CATEGORIES.FOOD },
  { name: "National Mason Jar Day", month: 11, day: 30, category: CATEGORIES.FUN },
  // December: Christmas, snow, cookies, new year (cross-ref: NDC, National Today)
  { name: "National Pie Day (December)", month: 12, day: 1, category: CATEGORIES.FOOD },
  { name: "National Fritters Day", month: 12, day: 2, category: CATEGORIES.FOOD },
  { name: "National Roof Over Your Head Day", month: 12, day: 3, category: CATEGORIES.FUN },
  { name: "National Cookie Day", month: 12, day: 4, category: CATEGORIES.FOOD },
  { name: "National Sacher Torte Day", month: 12, day: 5, category: CATEGORIES.FOOD },
  { name: "National Gazpacho Day", month: 12, day: 6, category: CATEGORIES.FOOD },
  { name: "National Pearl Harbor Remembrance Day", month: 12, day: 7, category: CATEGORIES.FEDERAL },
  { name: "National Brownie Day", month: 12, day: 8, category: CATEGORIES.FOOD },
  { name: "National Pastry Day", month: 12, day: 9, category: CATEGORIES.FOOD },
  { name: "National Lager Day", month: 12, day: 10, category: CATEGORIES.FOOD },
  { name: "National Noodle Ring Day", month: 12, day: 11, category: CATEGORIES.FOOD },
  { name: "National Gingerbread House Day", month: 12, day: 12, category: CATEGORIES.FUN },
  { name: "National Cocoa Day", month: 12, day: 13, category: CATEGORIES.FOOD },
  { name: "National Bouillabaisse Day", month: 12, day: 14, category: CATEGORIES.FOOD },
  { name: "National Cupcake Day", month: 12, day: 15, category: CATEGORIES.FOOD },
  { name: "National Chocolate Covered Anything Day", month: 12, day: 16, category: CATEGORIES.FOOD },
  { name: "National Maple Syrup Day", month: 12, day: 17, category: CATEGORIES.FOOD },
  { name: "National Roast Suckling Pig Day", month: 12, day: 18, category: CATEGORIES.FOOD },
  { name: "National Hard Candy Day", month: 12, day: 19, category: CATEGORIES.FOOD },
  { name: "National Sangria Day", month: 12, day: 20, category: CATEGORIES.FOOD },
  { name: "National Hamburger Day (December)", month: 12, day: 21, category: CATEGORIES.FOOD },
  { name: "National Date Nut Bread Day", month: 12, day: 22, category: CATEGORIES.FOOD },
  { name: "National Roots Day", month: 12, day: 23, category: CATEGORIES.CULTURAL },
  { name: "National Eggnog Day", month: 12, day: 24, category: CATEGORIES.FOOD },
  { name: "Christmas Day", month: 12, day: 25, category: CATEGORIES.FEDERAL },
  { name: "National Candy Cane Day", month: 12, day: 26, category: CATEGORIES.FOOD },
  { name: "National Fruitcake Day", month: 12, day: 27, category: CATEGORIES.FOOD },
  { name: "National Chocolate Candy Day", month: 12, day: 28, category: CATEGORIES.FOOD },
  { name: "National Pepper Pot Day", month: 12, day: 29, category: CATEGORIES.FOOD },
  { name: "National Bicarbonate of Soda Day", month: 12, day: 30, category: CATEGORIES.FUN },
  { name: "New Year's Eve", month: 12, day: 31, category: CATEGORIES.CULTURAL },
];

/**
 * Nth-weekday rules: { name, month, nth (1-4 or -1 for last), weekday (0=Sun .. 6=Sat), category, themeId? }
 * weekday: 0=Sunday, 1=Monday, 2=Tuesday, 3=Wednesday, 4=Thursday, 5=Friday, 6=Saturday
 */
const NTH_WEEKDAY = [
  { name: "Martin Luther King Jr. Day", month: 1, nth: 3, weekday: 1, category: CATEGORIES.FEDERAL, themeId: "mlk" },
  { name: "Presidents Day", month: 2, nth: 3, weekday: 1, category: CATEGORIES.FEDERAL },
  { name: "Mother's Day", month: 5, nth: 2, weekday: 0, category: CATEGORIES.CULTURAL, themeId: "mothers" },
  { name: "Memorial Day", month: 5, nth: -1, weekday: 1, category: CATEGORIES.FEDERAL, themeId: "memorial" },
  { name: "National Doughnut Day", month: 6, nth: 1, weekday: 5, category: CATEGORIES.FOOD },
  { name: "Father's Day", month: 6, nth: 3, weekday: 0, category: CATEGORIES.CULTURAL, themeId: "fathers" },
  { name: "National Ice Cream Day", month: 7, nth: 3, weekday: 0, category: CATEGORIES.FOOD },
  { name: "National Hot Dog Day", month: 7, nth: 3, weekday: 3, category: CATEGORIES.FOOD },
  { name: "Labor Day", month: 9, nth: 1, weekday: 1, category: CATEGORIES.FEDERAL, themeId: "labor" },
  { name: "National Grandparents Day", month: 9, nth: 1, weekday: 0, category: CATEGORIES.CULTURAL },
  { name: "National Teacher Day", month: 5, nth: 1, weekday: 2, category: CATEGORIES.CULTURAL },
  { name: "National Children's Day", month: 6, nth: 2, weekday: 0, category: CATEGORIES.CULTURAL },
  { name: "Take Your Child to Work Day", month: 4, nth: 4, weekday: 4, category: CATEGORIES.FUN },
  { name: "National Taco Day", month: 10, nth: 1, weekday: 2, category: CATEGORIES.FOOD },
  { name: "Columbus Day / Indigenous Peoples' Day", month: 10, nth: 2, weekday: 1, category: CATEGORIES.FEDERAL },
  { name: "Thanksgiving", month: 11, nth: 4, weekday: 4, category: CATEGORIES.FEDERAL, themeId: "thanksgiving" },
];

/** Easter (Sunday) — verified per DATE-VERIFICATION-SOURCES. Forward-looking 2026–2028; extend as needed. */
const EASTER_APPROX = [
  { year: 2026, month: 4, day: 5 },
  { year: 2027, month: 3, day: 28 },
  { year: 2028, month: 4, day: 16 },
];

function getNthWeekdayInMonth(year, month, nth, weekday) {
  if (nth === -1) {
    const last = new Date(year, month, 0);
    let d = last.getDate();
    while (new Date(year, month - 1, d).getDay() !== weekday) d--;
    return { month, day: d };
  }
  const first = new Date(year, month - 1, 1);
  const firstWeekday = first.getDay();
  const firstOccurrence = 1 + ((weekday - firstWeekday + 7) % 7);
  const day = firstOccurrence + (nth - 1) * 7;
  return { month, day };
}

/**
 * Get all observances for a given year (fixed + computed nth-weekday + Easter).
 * Returns array of { name, month, day, category, themeId? }.
 * @param {number} year
 * @param {string|string[]|null} [categoryFilter] - optional: single category or array of categories to include
 */
function getObservancesForYear(year, categoryFilter = null) {
  const list = [];
  const filterSet = categoryFilter
    ? new Set(Array.isArray(categoryFilter) ? categoryFilter : [categoryFilter])
    : null;

  for (const o of FIXED) {
    if (filterSet && !filterSet.has(o.category)) continue;
    list.push({
      name: o.name,
      month: o.month,
      day: o.day,
      category: o.category,
      themeId: o.themeId,
    });
  }
  for (const o of NTH_WEEKDAY) {
    if (filterSet && !filterSet.has(o.category)) continue;
    const { month, day } = getNthWeekdayInMonth(year, o.month, o.nth, o.weekday);
    list.push({
      name: o.name,
      month,
      day,
      category: o.category,
      themeId: o.themeId,
    });
  }
  const easter = EASTER_APPROX.find((e) => e.year === year);
  if (easter && (!filterSet || filterSet.has(CATEGORIES.CULTURAL))) {
    list.push({
      name: "Easter Sunday",
      month: easter.month,
      day: easter.day,
      category: CATEGORIES.CULTURAL,
      themeId: "easter",
    });
  }
  return list.sort((a, b) => (a.month !== b.month ? a.month - b.month : a.day - b.day));
}

/**
 * Get observances that fall on or after fromDate and within the next N days.
 * Forward-looking only: pass the current date (e.g. 2026-02-04) so we never suggest past holidays.
 * @param {Date|string|number} fromDate - current/reference date (e.g. "2026-02-04")
 * @param {number} [daysAhead=14]
 * @param {string|string[]|null} [categoryFilter] - optional filter by category
 */
function getUpcoming(fromDate, daysAhead = 14, categoryFilter = null) {
  const from = new Date(fromDate);
  from.setHours(0, 0, 0, 0);
  const to = new Date(from);
  to.setDate(to.getDate() + daysAhead);
  const year = from.getFullYear();
  const obs = getObservancesForYear(year, categoryFilter);
  const next = obs.filter((o) => {
    const d = new Date(year, o.month - 1, o.day);
    d.setHours(0, 0, 0, 0);
    return d >= from && d <= to;
  });
  return next;
}

export {
  CATEGORIES,
  FIXED,
  NTH_WEEKDAY,
  EASTER_APPROX,
  getObservancesForYear,
  getUpcoming,
};
